# Generated by Django 4.1.7 on 2024-04-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MusicPlayer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="image_url",
            field=models.CharField(default="SOME STRING", max_length=500),
        ),
        migrations.AddField(
            model_name="song",
            name="movie",
            field=models.CharField(default="SOME STRING", max_length=255),
        ),
    ]
